eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
server:
  port: 8770
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: FEIGN-CLIENT-ONE
    api-b:
      path: /api-b/**
      serviceId: FEIGN-CLIENT-TWO
hystrix: #hystrix配置
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon: #ribbon负载均衡参数配置
  ReadTimeout: 2000
  ConnectTimeout: 2000